theme:
  active: 60, 74, 174
  banner: 60, 74, 174
  error_border: Red
  error_text: LightRed
  header: White
  hint: 39, 51, 209
  hovered: 39, 51, 209
  inactive: Gray
  playbar_background: Black
  playbar_progress: 60, 74, 174
  playbar_progress_text: 192, 192, 193
  playbar_text: White
  selected: 60, 74, 174
  text: 255, 255, 255
